// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn2tLMPxrJtdF0ksRfWbn8AbK0hzGZ1uQ',
    appId: '1:313818767229:web:3ffa4c0b5b57e15b5df614',
    messagingSenderId: '313818767229',
    projectId: 'rapiven',
    authDomain: 'rapiven.firebaseapp.com',
    storageBucket: 'rapiven.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdKODMTE-QKmvQyP3FSkKmKv1_r3EDaRg',
    appId: '1:313818767229:android:4c644da7c75e26815df614',
    messagingSenderId: '313818767229',
    projectId: 'rapiven',
    storageBucket: 'rapiven.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT9aMkCORSLm50nk_a5BT9_REg_9Jpqjg',
    appId: '1:313818767229:ios:ddd00e3ae69404a05df614',
    messagingSenderId: '313818767229',
    projectId: 'rapiven',
    storageBucket: 'rapiven.firebasestorage.app',
    iosBundleId: 'com.example.rapivenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT9aMkCORSLm50nk_a5BT9_REg_9Jpqjg',
    appId: '1:313818767229:ios:ddd00e3ae69404a05df614',
    messagingSenderId: '313818767229',
    projectId: 'rapiven',
    storageBucket: 'rapiven.firebasestorage.app',
    iosBundleId: 'com.example.rapivenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn2tLMPxrJtdF0ksRfWbn8AbK0hzGZ1uQ',
    appId: '1:313818767229:web:f129d0a18f2dc1035df614',
    messagingSenderId: '313818767229',
    projectId: 'rapiven',
    authDomain: 'rapiven.firebaseapp.com',
    storageBucket: 'rapiven.firebasestorage.app',
  );

}